# Rustfmt configuration for NORC project
# Ensures consistent code formatting across the project
# Using only stable rustfmt features for CI compatibility

# Edition and basic formatting settings
edition = "2024"
use_field_init_shorthand = true
use_try_shorthand = true

# String and array formatting
max_width = 100

# Struct and enum formatting
array_width = 60
chain_width = 60

# Miscellaneous
remove_nested_parens = true