# codecov.yml - Codecov configuration
# Documentation: https://docs.codecov.com/docs/codecov-yaml

coverage:
  precision: 2
  round: down
  range: "80...100"
  
  status:
    project:
      default:
        target: 80%
        threshold: 2%
        if_ci_failed: error
    
    patch:
      default:
        target: 80%
        threshold: 5%
        if_ci_failed: error

comment:
  layout: "reach,diff,flags,tree,footer"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true

ignore:
  - "target/**/*"
  - "tests/**/*"
  - "benches/**/*"
  - "**/tests.rs"
  - "**/test_*.rs"

github_checks:
  annotations: true
