# cargo-deny configuration for dependency auditing and license compliance

[graph]
# Allow multiple versions of these crates due to ecosystem fragmentation
multiple-versions = "allow"

[licenses]
# List of allowed licenses for dependencies
allow = [
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "MIT",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "ISC",
    "Unicode-DFS-2016",
]

# List of explicitly disallowed licenses
deny = [
    "GPL-2.0",
    "GPL-3.0",
    "AGPL-1.0",
    "AGPL-3.0",
    "LGPL-2.0",
    "LGPL-2.1",
    "LGPL-3.0",
]

# Confidence threshold for license detection
confidence-threshold = 0.8

# Some packages don't have license files but are MIT/Apache-2.0
exceptions = [
    { allow = ["Unicode-DFS-2016"], name = "unicode-ident" },
]

[bans]
# Deny multiple versions of these specific crates
multiple-versions = "warn"
wildcards = "allow"

# Explicitly deny these crates
deny = [
    # Insecure or deprecated cryptography
    { name = "openssl", reason = "Use rustls instead for better security guarantees" },
    { name = "native-tls", reason = "Use rustls for consistent cross-platform behavior" },
    
    # Unsafe or problematic crates
    { name = "diesel", reason = "Not needed for our use case, adds complexity" },
]

# Skip these crates from duplicate version checking
skip = [
    # These commonly have version conflicts in the ecosystem
    { name = "windows-sys" },
    { name = "windows_x86_64_msvc" },
]

# Skip checking these trees entirely
skip-tree = []

[advisories]
# Sources for security advisories
db-path = "~/.cargo/advisory-db"
db-urls = ["https://github.com/rustsec/advisory-db"]

# Vulnerability database settings
vulnerability = "deny"
unmaintained = "warn"
yanked = "warn"
notice = "warn"

# Ignore specific advisories (with justification)
ignore = [
    # Add specific RUSTSEC-YYYY-NNNN advisories here if needed with justification
]

[sources]
# Only allow crates.io and git sources
unknown-registry = "warn"
unknown-git = "warn"

# Allow git dependencies for development/preview versions
allow-git = []