# cargo-deny configuration
# Documentation: https://embarkstudios.github.io/cargo-deny/

[advisories]
# The path where the advisory database is cloned/fetched into
db-path = "~/.cargo/advisory-db"
# The url(s) of the advisory databases to use
db-urls = ["https://github.com/rustsec/advisory-db"]
# The lint level for security vulnerabilities
vulnerability = "deny"
# The lint level for unmaintained crates
unmaintained = "warn"
# The lint level for crates that have been yanked from their source registry
yanked = "deny"
# The lint level for crates with security notices
notice = "warn"
# Ignore specific advisories
ignore = [
    #"RUSTSEC-0000-0000",
]

[licenses]
# The lint level for crates which do not have a detectable license
unlicensed = "deny"
# List of explicitly allowed licenses
allow = [
    "MIT",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "ISC",
    "Unicode-DFS-2016",
    "CC0-1.0",
]
# The confidence threshold for detecting a license from license text
confidence-threshold = 0.8
# Allow 1 or more licenses on a per-crate basis
exceptions = [
    # OpenSSL has its own license
    { allow = ["OpenSSL"], name = "ring" },
]

[licenses.private]
# If true, ignores workspace crates that aren't published
ignore = false
# One or more private registries that you might publish crates to
registries = []

[bans]
# Lint level for when multiple versions of the same crate are detected
multiple-versions = "warn"
# Lint level for when a crate version requirement is `*`
wildcards = "deny"
# The graph highlighting used when creating dotgraphs for crates with multiple versions
highlight = "all"
# List of crates that are allowed
allow = []
# List of crates to deny
deny = [
    # Vulnerable or malicious crates can be denied here
]
# Certain crates/versions that will be skipped when doing duplicate detection
skip = []
# Similarly named crates that are allowed
skip-tree = []

[sources]
# Lint level for what to happen when a crate from a git repository that is not in the allow list is encountered
unknown-git = "warn"
# Lint level for what to happen when a crate from a registry that is not in the allow list is encountered
unknown-registry = "deny"
# List of URLs for allowed git repositories
allow-git = []
# List of URLs for allowed registries
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
