# cargo-deny configuration for NavaTron NORC workspace

[advisories]
# Fail the build on unpatched vulnerabilities
vulnerability = "deny"
unmaintained = "warn"
yanked = "warn"
notice = "warn"
ignore = []

[licenses]
# Allow a curated, OSI-approved set only
allow = [
  "Apache-2.0",
  "MIT",
  "BSD-2-Clause",
  "BSD-3-Clause",
  "ISC",
  "Zlib",
  "Unicode-DFS-2016",
  "CC0-1.0"
]
# Deny copyleft / strong reciprocal to simplify redistribution until audited
deny = [
  "AGPL-3.0",
  "GPL-3.0",
  "GPL-2.0",
  "LGPL-3.0",
  "LGPL-2.1"
]
# Ban unknown / unlicensed
unlicensed = "deny"

[bans]
multiple-versions = "warn"
wildcards = "deny"
denied = []
# Example: enforce single version of critical crypto crates (add once duplicates appear)
# allow = [
#   { name = "blake3", version = "1.5.4" }
# ]

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
# No git sources yet; if added, enumerate explicitly
allow-git = []

[features]
# Warn on unused optional features creeping in
unused = "warn"

[[targets]]
# Apply to all targets
triple = "*"
