# rustfmt configuration
# Documentation: https://rust-lang.github.io/rustfmt/

edition = "2024"
max_width = 100
hard_tabs = false
tab_spaces = 4
newline_style = "Unix"
use_small_heuristics = "Default"
reorder_imports = true
reorder_modules = true
remove_nested_parens = true
format_strings = false
format_macro_matchers = true
format_macro_bodies = true
normalize_comments = true
normalize_doc_attributes = true
wrap_comments = true
comment_width = 80
match_block_trailing_comma = false
trailing_comma = "Vertical"
trailing_semicolon = true
use_field_init_shorthand = true
use_try_shorthand = true
fn_single_line = false
where_single_line = false
imports_indent = "Block"
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
binop_separator = "Front"
