[package]
name = "norc-client-core"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
description = "NORC Client Core - Headless client library"
keywords = ["client", "norc", "chat"]
