[package]
name = "norc-cli"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
description = "NORC CLI utilities - Command line interface helpers"
keywords = ["cli", "clap", "config"]
