[package]
name = "norc-transport"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
description = "NORC Transport layer - TLS, WebSocket, and connection management"
keywords = ["transport", "tls", "websocket", "networking"]
