[package]
name = "norc-protocol"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
description = "NORC Protocol implementation - message types, codecs, and versioning"
keywords = ["norc", "protocol", "messaging", "encryption"]
