[package]
name = "norc-server-core"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
description = "NORC Server Core - Headless server library"
keywords = ["server", "norc", "federation"]
