# NORC Server Configuration Example
# Comprehensive security and certificate configuration

organization_id = "example.org"

[network]
bind_address = "0.0.0.0"
bind_port = 8443
federation_address = "0.0.0.0"
federation_port = 8444
enable_tls = true
tls_cert_path = "/etc/norc/certs/server.crt"
tls_key_path = "/etc/norc/certs/server.key"
enable_websocket = true
enable_quic = false

[security]
organization_id = "example.org"
default_trust_level = "Basic"
enable_pq_crypto = false
key_rotation_interval_secs = 3600  # 1 hour
strict_cert_validation = true
enable_hsm = false

# TLS Security Configuration
[security.tls]
require_mutual_tls = true
min_tls_version = "1.3"
enable_session_resumption = true
session_ticket_rotation_secs = 86400  # 24 hours

# Trusted CA certificates for client/federation verification
trusted_ca_certs = [
    "/etc/norc/certs/federation-ca.crt",
    "/etc/norc/certs/client-ca.crt"
]

# Allowed cipher suites (empty = secure defaults)
allowed_cipher_suites = []

# Certificate Pinning Configuration
[security.tls.pinning]
enabled = true
mode = "strict"  # or "relaxed"

# SHA-256 fingerprints of pinned certificates
# Generate with: openssl x509 -in cert.pem -noout -fingerprint -sha256
pins = [
    "sha256:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    "sha256:BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB"
]

# Alternative: Pin certificate files (will be fingerprinted automatically)
pin_cert_files = [
    # "/etc/norc/certs/pinned/partner1.crt",
    # "/etc/norc/certs/pinned/partner2.crt"
]

# SPKI (Subject Public Key Info) pinning (HPKP-style)
enable_spki_pins = false
spki_pins = []

# Backup pins for key rotation
backup_pins = [
    # "sha256:CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC"
]

# Maximum pin age (days, 0 = no limit)
max_pin_age_days = 0

# Certificate Revocation Checking
[security.revocation]
enable_ocsp = true
enable_crl = true
timeout_secs = 10
max_crl_size_bytes = 10485760  # 10 MB
fail_on_unknown = false  # Set true for strict security
ocsp_cache_duration_secs = 3600   # 1 hour
crl_cache_duration_secs = 86400   # 24 hours

# OCSP Stapling Configuration
[security.revocation.ocsp_stapling]
enabled = false
# responder_url = "http://ocsp.example.org"  # Override if not in certificate
refresh_before_expiry_secs = 3600  # Refresh 1 hour before expiration

[observability]
log_level = "info"
log_format = "json"
log_file_path = "/var/log/norc/server.log"
enable_metrics = true
metrics_address = "0.0.0.0"
metrics_port = 9090
enable_tracing = false
tracing_endpoint = "http://localhost:4317"
tracing_sample_rate = 1.0

[federation]
enable_federation = true
discovery_method = "static"

# Federation Partners
[[federation.partners]]
organization_id = "partner1.org"
address = "federation.partner1.org:8444"
trust_level = "Full"
mutual_tls = true

[[federation.partners]]
organization_id = "partner2.org"
address = "federation.partner2.org:8444"
trust_level = "Basic"
mutual_tls = true

[limits]
max_connections = 50000
max_message_size = 16777216  # 16 MB
rate_limit_per_connection = 100
max_memory_per_connection = 1048576  # 1 MB
worker_threads = 0  # 0 = auto-detect

[daemon]
daemonize = false
pid_file = "/var/run/norc/norc.pid"
auto_restart = true
max_restarts = 3
restart_cooldown_secs = 30

[storage]
data_dir = "/var/lib/norc"
enable_persistence = true
snapshot_interval_secs = 300
max_snapshots = 10
