# Development NORC Server Configuration

[network]
bind_address = "127.0.0.1"
port = 8443
max_connections = 100
connection_timeout_secs = 30
ipv6_enabled = false

[tls]
# Disable TLS for local development
enabled = false

[logging]
level = "debug"
format = "pretty"
# Log to stdout for development
rotation = false

[storage]
data_dir = "./dev-data"
max_disk_usage_mb = 1024
compression_enabled = false
backup_interval_hours = 0
backup_retention = 3

[daemon]
pid_file = "./dev-norc-server.pid"
auto_restart = false
max_restarts = 3
restart_cooldown_secs = 5