# NORC Server Configuration

[network]
# Address to bind the server to (IPv4 or IPv6)
bind_address = "127.0.0.1"
# Port to listen on for NORC protocol connections
port = 8443
# Maximum number of concurrent connections
max_connections = 1000
# Connection timeout in seconds
connection_timeout_secs = 30
# Enable IPv6 support
ipv6_enabled = true

[tls]
# Enable TLS encryption
enabled = true
# Path to TLS certificate file (PEM format)
cert_file = "./certs/server.crt"
# Path to TLS private key file (PEM format)
key_file = "./certs/server.key"
# Path to CA certificate file for client verification (optional)
ca_file = "./certs/ca.crt"
# Require client certificates for mutual TLS
require_client_certs = false
# Minimum TLS version (1.2 or 1.3)
min_version = "1.3"

[logging]
# Log level: trace, debug, info, warn, error
level = "info"
# Log format: json, pretty, compact
format = "json"
# Log file path (if not specified, logs to stdout)
file = "./logs/norc-server.log"
# Enable log file rotation
rotation = true
# Maximum log file size in MB before rotation
max_size_mb = 100
# Number of rotated log files to keep
max_files = 10

[storage]
# Data directory for persistent storage
data_dir = "./data"
# Maximum disk usage in MB (10GB default)
max_disk_usage_mb = 10240
# Enable compression for stored data
compression_enabled = true
# Backup interval in hours (0 = disabled)
backup_interval_hours = 24
# Number of backups to retain
backup_retention = 7

[daemon]
# PID file path
pid_file = "./norc-server.pid"
# User to run as (Unix only, leave empty for current user)
user = ""
# Group to run as (Unix only, leave empty for current group)
group = ""
# Working directory (leave empty for current directory)
working_dir = ""
# Enable auto-restart on crash
auto_restart = true
# Maximum restart attempts before giving up
max_restarts = 5
# Restart cooldown period in seconds
restart_cooldown_secs = 60