# Production NORC Server Configuration

[network]
# Bind to all interfaces for production
bind_address = "0.0.0.0"
port = 8443
max_connections = 5000
connection_timeout_secs = 60
ipv6_enabled = true

[tls]
enabled = true
# Use Let's Encrypt or your organization's certificates
cert_file = "/etc/ssl/certs/norc-server.crt"
key_file = "/etc/ssl/private/norc-server.key"
ca_file = "/etc/ssl/certs/ca-bundle.crt"
require_client_certs = false
min_version = "1.3"

[logging]
level = "info"
format = "json"
# Log to system location
file = "/var/log/norc-server/server.log"
rotation = true
max_size_mb = 500
max_files = 30

[storage]
# Use dedicated data partition
data_dir = "/var/lib/norc-server"
# 100GB max storage
max_disk_usage_mb = 102400
compression_enabled = true
backup_interval_hours = 6
backup_retention = 14

[daemon]
# System PID file location
pid_file = "/var/run/norc-server.pid"
# Run as dedicated service user
user = "norc-server"
group = "norc-server"
working_dir = "/var/lib/norc-server"
auto_restart = true
max_restarts = 10
restart_cooldown_secs = 30