[package]
name = "norc-tui"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
description = "NORC TUI components - Terminal user interface"
keywords = ["tui", "terminal", "ui"]
